/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Npc } from "./Npc";
import { NpcCountArgs } from "./NpcCountArgs";
import { NpcFindManyArgs } from "./NpcFindManyArgs";
import { NpcFindUniqueArgs } from "./NpcFindUniqueArgs";
import { DeleteNpcArgs } from "./DeleteNpcArgs";
import { NpcService } from "../npc.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Npc)
export class NpcResolverBase {
  constructor(
    protected readonly service: NpcService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Npc",
    action: "read",
    possession: "any",
  })
  async _npcsMeta(
    @graphql.Args() args: NpcCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Npc])
  @nestAccessControl.UseRoles({
    resource: "Npc",
    action: "read",
    possession: "any",
  })
  async npcs(@graphql.Args() args: NpcFindManyArgs): Promise<Npc[]> {
    return this.service.npcs(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Npc, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Npc",
    action: "read",
    possession: "own",
  })
  async npc(@graphql.Args() args: NpcFindUniqueArgs): Promise<Npc | null> {
    const result = await this.service.npc(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Npc)
  @nestAccessControl.UseRoles({
    resource: "Npc",
    action: "delete",
    possession: "any",
  })
  async deleteNpc(@graphql.Args() args: DeleteNpcArgs): Promise<Npc | null> {
    try {
      return await this.service.deleteNpc(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
