/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Character } from "./Character";
import { CharacterCountArgs } from "./CharacterCountArgs";
import { CharacterFindManyArgs } from "./CharacterFindManyArgs";
import { CharacterFindUniqueArgs } from "./CharacterFindUniqueArgs";
import { DeleteCharacterArgs } from "./DeleteCharacterArgs";
import { CharacterService } from "../character.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Character)
export class CharacterResolverBase {
  constructor(
    protected readonly service: CharacterService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Character",
    action: "read",
    possession: "any",
  })
  async _charactersMeta(
    @graphql.Args() args: CharacterCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Character])
  @nestAccessControl.UseRoles({
    resource: "Character",
    action: "read",
    possession: "any",
  })
  async characters(
    @graphql.Args() args: CharacterFindManyArgs
  ): Promise<Character[]> {
    return this.service.characters(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Character, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Character",
    action: "read",
    possession: "own",
  })
  async character(
    @graphql.Args() args: CharacterFindUniqueArgs
  ): Promise<Character | null> {
    const result = await this.service.character(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Character)
  @nestAccessControl.UseRoles({
    resource: "Character",
    action: "delete",
    possession: "any",
  })
  async deleteCharacter(
    @graphql.Args() args: DeleteCharacterArgs
  ): Promise<Character | null> {
    try {
      return await this.service.deleteCharacter(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
